### ISSUE TITLE
Transfer the issues of the old repo to the new one

### ISSUE THREAD

**Issue by dashohoxha** [EasyGnuPG/egpg-1#4]
Try to find some tools that can automate the transfer of old repo issues to the new one (including comments, references, etc.) GitHub itself does not offer this service from its interface.

**Comment by dashohoxha** [comment]
I tried with this one: https://github.com/ahadik/git_mover
But somehow I failed. Maybe I did not do something right. I will try it again later.
In the end we are going to do what you suggest.

**Comment by dashohoxha** [comment]
I tried it again and I couldn't make it work. I give up.
@sourabhtk37 please do it your own way.

**Comment by diveshuttam** [comment]
Hi @dashohoxha ,
GitHub does provide an option to transfer a repository from one organization/user to the other. You can find it in the settings tab of the old repository. This will migrate all the issues,pr etc. GitHub will also redirect the older repo's url's to the new one.
Also note that since you have made this repository with name `egpg` here, we will have to delete this for the transfer as the names have to be unique within an organization.
You can find more about this [here](https://help.github.com/articles/about-repository-transfers/) . I used it for [termicoder](https://github.com/diveshuttam/termicoder).

**Comment by dashohoxha** [comment]
Thanks, it worked. By the way, I missed the suggestion of @sourabhtk37 
Now I have to do all the work again (creating those new issues, etc.)
